---
# tasks file for roles/database
- name: Run Database container
  docker_container:
    name: database
    image: kevindang01/database:latest
    networks:
      - name: my_network
        aliases: ['database']
    # Add other necessary parameters (e.g., environment variables, volumes, ports, etc.)
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd 
    volumes:
      - my_volume:/var/liv/postgresql/data