#- hosts: all
#  gather_facts: false
#  become: yes

#  tasks:
#    - name: Test connection
#      ping:

- hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Import Docker role
      import_role:
        name: docker
    - name: Import network role
      import_role:
        name: network    
    - name: Import volume role
      import_role:
        name: volume    
    - name: Import database role
      import_role:
        name: database
    - name: Import backend role
      import_role:
        name: backend
    - name: Import httpd role
      import_role:
        name: httpd
    #- name: Import frontend role
    #  import_role:
    #    name: frontend