name: Build and Push Backend Docker Image

on:
  workflow_run:
    branches: [main]
    workflows:
      - "Test Backend"
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04

    steps:
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./TP1/backend
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend
          push: true