name: CI devops 2023

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build and test with Maven
        run: |
          cd TP1/backend
          mvn test
          
  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
	  # run only when code is compiling and tests are passing
	  runs-on: ubuntu-22.04

	  # steps to perform in job
	  steps:
	    - name: Checkout code
	      uses: actions/checkout@v2.5.
	      
	    - name: Build image and push backend
          uses: docker/build-push-action@v3
          run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          with:
		    # relative path to the place where source code with Dockerfile is located
		    context: ./backend
		    # Note: tags have to be all lower-case
		    tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops/
			# build on feature branches, push only on main branch
            push: ${{ github.ref == 'refs/heads/main' }}

	    - name: Build image and push database
          uses: docker/build-push-action@v3
          with:
		    # relative path to the place where source code with Dockerfile is located
		    context: ./database
		    # Note: tags have to be all lower-case
		    tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops/database
		    # build on feature branches, push only on main branch
            push: ${{ github.ref == 'refs/heads/main' }}

	    - name: Build image and push httpd
	      uses: docker/build-push-action@v3
          with:
		    # relative path to the place where source code with Dockerfile is located
		    context: ./http-server
		    # Note: tags have to be all lower-case
		    tags: ${{secrets.DOCKERHUB_USERNAME}}/tp-devops/httpd
		    # build on feature branches, push only on main branch
            push: ${{ github.ref == 'refs/heads/main' }}


